site_name: SceneBuilder Manual
site_description: 'SceneBuilderの公式マニュアルです!'
site_author: 'HIKKY'

theme:
  favicon: images/VketCloudIcon.png
  logo: images/VketCloudIcon.png
  name: material
  palette:
  - scheme: default
    primary: custom
    accent: custom
    toggle:
        icon: material/toggle-switch-off-outline
        name: ダークモードに切り替えます。
  - scheme: slate
    primary: custom
    accent: custom
    toggle:
        icon: material/toggle-switch
        name: ライトモードに切り替えます。
  features:
    - navigation.indexes
    - header.autohide
    - search.suggest
    - search.highlight
  footer:
    logo: images/HikkyLogo.png
    copyright: ©HIKKY Co.,Ltd. All rights reserved.
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  nav_style: dark
  custom_dir: custom_theme

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  version:
    provider: mike
    default: latest
    homepage: https://www.hikky.co.jp/vketcloud

use_directory_urls: false

plugins:
  - search:
      lang: 
        - en
        - ja
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: null
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          name: English
          build: true
        - locale: ja
          name: 日本語
          build: true
          default: true
          nav_translations:
            Introduction: はじめに
            Glossary: 用語集
            Getting Started: SceneBuilderの基本
            SceneBuilder Setup: SceneBuilderのセットアップ
            Reformatting Assets: アセットの再フォーマット
            How to Import Items: アイテムの読み込み・配置
            How to Create Gimmicks: ギミックを作成する
            World Upload: ワールドをアップロードする
            Controls and Properties: 各種操作・設定
            Builder Window Overview: 各ウィンドウの機能
            Using the Manipulator: マニピュレーターの操作方法
            Camera Controls: カメラの操作方法
            Item Configuration: アイテムごとのプロパティ
            Creation Tips: ワールド制作のためのTips
            Light and RefProbe Baking: アセットのライトマップとRefProbeのベイクについて
            Actions: アクションについて
            Release Note: リリースノート      

markdown_extensions:
    - admonition
    - codehilite
    - attr_list

nav:
- Introduction: index.md
- Glossary: Glossary/Glossary.md
- Getting Started:
  - SceneBuilder Setup: GettingStarted/SceneBuilderSetup.md
  - Reformatting Assets: GettingStarted/ReformattingAssets.md
  - How to Import Items: GettingStarted/ImportItems.md
  - How to Create Gimmicks: GettingStarted/CreateGimmicks.md
  - World Upload: GettingStarted/WorldUpload.md
- Controls and Properties:
  - Builder Window Overview: ControlsProperties/WindowOverview.md
  - Using the Manipulator: ControlsProperties/Manipulator.md
  - Camera Controls: ControlsProperties/CameraControls.md
  - Item Configuration: ControlsProperties/ItemConfig.md
- Creation Tips:
  - Light and RefProbe Baking: CreationTips/LightRefProbe.md
# - Actions:
# - HeliScript:
- Release Note:
  - SceneBuilder(α):
    - v0.1: releasenote/releasenote-0.1.md
